# Pre-commit configuration for AgentROS
# Optimized for local development with fast feedback

default_stages: [commit]
fail_fast: true
minimum_pre_commit_version: 3.0.0

repos:
  # Local repository hooks (fastest)
  - repo: local
    hooks:
      # Quick Python syntax check
      - id: python-check-ast
        name: Check Python AST
        entry: python -m py_compile
        language: system
        files: \.py$
        stages: [commit]
      
      # Quick import sorting
      - id: isort-check
        name: isort (check only)
        entry: isort --check-only --diff
        language: system
        files: \.py$
        stages: [commit]

  # Code formatting (auto-fix)
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: Format Python code (black)
        language_version: python3
        stages: [commit]
        args: [--line-length=88]

  # Fast linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        name: Lint Python code (ruff)
        args: [--fix, --exit-non-zero-on-fix]
        stages: [commit]

  # Basic file checks (fast)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]

  # Type checking (only on manual run to keep commits fast)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        name: Type check Python code (mypy)
        stages: [manual]
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --strict]

# Configuration for development efficiency
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [mypy]  # Skip slow checks in CI
  submodules: false
